### ISSUE TITLE
Zeplin support

### ISSUE THREAD

**Issue by samwalshnz** [pocka/storybook-addon-designs#10]
Is there any way that Zeplin designs could be embedded? 🤔

**Comment by vzaidman** [comment]
looks like not. they have an iframe policy that prevents it

**Comment by pocka** [comment]
@samwalshnz 
As @vzaidman said, we can't embed sites that have a same-origin policy. At the moment, you can embed designs on Zeplin by manually exporting them as images...

- [Make possible to integrate zeplin screens (with an iframe for example) in any other external source(Zeplin forums)](https://zeplin.uservoice.com/forums/255350-got-any-suggestions/suggestions/18416917-make-possible-to-integrate-zeplin-screens-with-an)
- [Zeplin API – to add zeplin screens to a custom webpage/guide(Zeplin forums)](https://zeplin.uservoice.com/forums/255350-got-any-suggestions/suggestions/33320281-zeplin-api-to-add-zeplin-screens-to-a-custom-web)

**Comment by dirtybit** [comment]
Hey all! 👋 

I just wanted to let you know that we launched the Zeplin API in beta last month. You can access resources on Zeplin through API and display them in the addon.

You can take a look the the [announcement post](https://blog.zeplin.io/tis-the-season-unwrapping-the-zeplin-api-ca89aa7c1ad8) and the [API docs](http://docs.zeplin.dev) for more details.

Feel free to ping us if you have questions!

**Comment by pocka** [comment]
I researched and tried Zeplin then designed an embedding process. Are you okay with this?

- Embed Zeplin **Screens**
  - Components can't because they don't have their URL
- Fetch a Screen image via API then embed it as `type: "image"`, so there are no guidelines nor comments
- Show links to open the design in Zeplin web/apps

```js
myStory.story = {
  parameters: {
    design: {
      type: 'zeplin',
      url: 'zpl://screen?pid=<PROJECT_ID>&sid=<SCREEN_ID>',
      // or web url (non shortened ver.)
      url: 'https://app.zeplin.io/project/<PROJECT_ID>/screen/<SCREEN_ID>',
      showLinks: false, // default = true
    }
  }
}
```

I want to hear an opinion from users for Zeplin or this addon. Any feedback is appreciated!

**Comment by pocka** [comment]
There is a Storybook addon from Zeplin guys! Added a link to the addon in README (abf8a4490605f42d7a436086a74aaad0f344d786).

https://github.com/mertkahyaoglu/storybook-zeplin
