### ISSUE TITLE
TypeError: Cannot read property 'debug' of undefined 

### ISSUE THREAD

**Issue by pruett** [pocka/storybook-addon-designs#101]
**Affected design types**

- [ ] `figma`
- [ ] `experimental-figspec`
- [ ] `link`
- [ ] `image`
- [ ] `iframe`

**Describe the bug**

**main.js**
```
module.exports = {
  stories: [
    '...'
  ],
  addons: [
    'storybook-addon-designs',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
  ],
};
```

**To Reproduce**

1. `./node-modules/.bin/start-storybook -p 6006`
2. See error in console

**Expected behavior**

Error-free render

**Screenshots**
![Screen Shot 2021-05-25 at 6 50 33 PM](https://user-images.githubusercontent.com/794809/119578222-1f1c0a80-bd8a-11eb-81f4-cb5a74b3752a.png)

![Screen Shot 2021-05-25 at 6 49 40 PM](https://user-images.githubusercontent.com/794809/119578148-014ea580-bd8a-11eb-9d47-29ce20f70b17.png)

**Environment**
Chrome

**Versions**

Paste the result of `npm list storybook-addon-designs` or `yarn list --pattern storybook-addon-designs` below.

```sh
❯ yarn list --pattern @storybook/ui
├─ @storybook/core@6.1.21
│  └─ @storybook/ui@6.1.21
├─ @storybook/ui@6.2.9
└─ roman-shared@3.0.0
   └─ @storybook/ui@5.3.21
```

**Comment by pocka** [comment]
Please fill in the issue template correctly. Also, make sure you have a matching version of `@storybook/*` packages.
