### ISSUE TITLE
Support multiple figma urls in a story

### ISSUE THREAD

**Issue by lazreg87** [pocka/storybook-addon-designs#102]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to support multiple figma design urls in a single story, since Figma lets you link to specific nodes in the design. 

Example usecase; be able to link to separate desktop and mobile design for one story 

**Describe the solution you'd like**
Support multiple figma design urls per story

**Describe alternatives you've considered**
I could split the story into desktop and mobile, but since you can define viewports, this seems like overkill.

**Design types**

- [x] `figma`
- [ ] `experimental-figspec`
- [ ] `link`
- [ ] `image`
- [ ] `iframe`

**Additional context**

**Comment by pocka** [comment]
You can embed more than one design assets (not only Figma, also links, images, and iframes) into one story by passing an array of objects. ([Example](https://pocka.github.io/storybook-addon-designs/?path=/docs/docs-advanced-usage--embed-multiple-designs#embed-multiple-designs))

If you do so, I'd recommend you to set a tab name via the `name` property.

```js
export const myStory = () => <MyComponent />

myStory.parameters = {
  design: [
    {
      name: 'Mobile',
      type: 'figma',
      url:
        'https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample',
    },
    {
      name: 'Desktop',
      type: 'figma',
      url:
        'https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample',
    },
  ],
}
```

**Comment by sauldeleon** [comment]
Hi! I don't know if I should reopen this. Im having a problem when including multiple `experimental-figspec` designs.

Only the first one in the array list is loading properly. The second one seems like blocked and cant even scroll in the figma iframe

**Comment by pocka** [comment]
@sauldeleon 
Can you open a new issue? It seems specific to figspec embed.

**Comment by sauldeleon** [comment]
Sure! here you go!
https://github.com/pocka/storybook-addon-designs/issues/122
