### ISSUE TITLE
Integration with angular 

### ISSUE THREAD

**Issue by iamtharun** [pocka/storybook-addon-designs#103]
How to use this plugin with Angular framework? I could not find any example. Most examples are on React

Is this plugin only for react ?

**Comment by pocka** [comment]
As [stated in the README](https://github.com/pocka/storybook-addon-designs/tree/a9ac39d7bfb32e2ff5ac8dcf3827473656e38ea6#requirements), you can use this addon with any frameworks (except React Native).

The usage is not specific to React: both [Parameters](https://storybook.js.org/docs/angular/writing-stories/parameters) and [Decorators](https://storybook.js.org/docs/angular/writing-stories/decorators) are Storybook's core concept, which is framework agnostic so you can use them with the same APIs across frameworks.

**Comment by iamtharun** [comment]
Hello @pocka Thanks for the reply. The only reason I had raised the question on here is I could not find any examples for Angular integration. As most examples are in React. It will be helpful if the documentation has examples of Angular as well.

**Comment by pocka** [comment]
Please read [the Storybook's official documents](https://storybook.js.org/docs/angular/get-started/whats-a-story) first.
Many Storybook Addons utilize Parameters and/or Decorators, which are the framework-agnostic concept of CSF (Storybook), hence there are no "docs for \<framework\>" unless the addon uses framework-specific features.

**Comment by iamtharun** [comment]
Hello @pocka , I have no issue in integrating storybook with Angular, its pretty smooth. The issue I'm having is when trying to integrate Angular with storybook-addon-design, with React I was able to achieve it. https://medium.com/storybookjs/storybook-figma-addon-7a399f094a0a
