### ISSUE TITLE
Figma properties panel

### ISSUE THREAD

**Issue by Tim-arts** [pocka/storybook-addon-designs#115]
Hello! I would like to know if it would be possible to add an option to display a properties panel from the figma iframe into Storybook?
![image](https://user-images.githubusercontent.com/10064887/127402438-1af4e6e5-2c36-4c12-8b1f-02c878d24816.png)

Something like this but displayed inside Storybook in order to help the front-end developer to know about these precious properties:

![example](https://user-images.githubusercontent.com/10064887/127403682-865990f6-d549-4ecb-afa4-1e5c97221f94.png)

**Comment by pocka** [comment]
Please use the Issue Template.

---

This addon uses the [Figma Live Embed Kit](https://www.figma.com/developers/embed), which is provided by Figma, for iframe embedding. If you want a feature in that, I would recommend you to submit a feature request to them (through "Submit Feedback" or "Contact Support").

However, there are ways if you don't mind using an external service or library.

- [Contrast](https://www.contrast.app/) can mirror Figma files and have [an official Storybook addon](https://github.com/toyboxsystems/storybook-contrast)
- the `experimental-figspec` type uses [figspec](https://github.com/pocka/figspec) ([working demo](https://figspec.netlify.app/?path=/story/components-figspec-file-viewer--defaults)) along with Figma REST API and have an inspector panel (this method requires you to include your Figma API Token into Storybook bundle file)

**Comment by Tim-arts** [comment]
Hello Pocka, thank you for your detailed answer.
I'm trying to set up the experimental-figspec but I can't make it work, I'm following this documentation: [](https://storybook-addon-designs-f8z5gt8iw.vercel.app/?path=/story/docs-figma-figspec-readme--page)

When I try to apply this into my project I get this error: 
![image](https://user-images.githubusercontent.com/10064887/127514304-8a4f6491-4b57-48ae-8e24-503d5cbfb0db.png)

So I believe I've set up a wrong configuration, but I can't get a documented working example. Is your Netlify application documented somewhere?

**Comment by pocka** [comment]
@Tim-arts Would you mind sharing the response body of `GET https://api.figma.com/v1/files/${fileKey}`?

**Comment by Tim-arts** [comment]
Hello @pocka, sure there it is:

<details>
  <summary>JSON response</summary>
  {
  "document": {
    "id": "0:0",
    "name": "Document",
    "type": "DOCUMENT",
    "children": [
      {
        "id": "0:1",
        "name": "Page 1",
        "type": "CANVAS",
        "children": [
          {
            "id": "2:2",
            "name": "Frame 1",
            "type": "FRAME",
            "blendMode": "PASS_THROUGH",
            "children": [
              {
                "id": "2:56",
                "name": "Button/Primary",
                "type": "FRAME",
                "blendMode": "PASS_THROUGH",
                "children": [
                  {
                    "id": "2:57",
                    "name": "Label",
                    "type": "TEXT",
                    "blendMode": "PASS_THROUGH",
                    "absoluteBoundingBox": {
                      "x": -315,
                      "y": -262,
                      "width": 33,
                      "height": 16
                    },
                    "constraints": {
                      "vertical": "TOP",
                      "horizontal": "LEFT"
                    },
                    "layoutAlign": "INHERIT",
                    "layoutGrow": 0,
                    "fills": [
                      {
                        "blendMode": "NORMAL",
                        "type": "SOLID",
                        "color": {
                          "r": 0.9529411792755127,
                          "g": 0.95686274766922,
                          "b": 0.95686274766922,
                          "a": 1
                        }
                      }
                    ],
                    "strokes": [],
                    "strokeWeight": 1,
                    "strokeAlign": "OUTSIDE",
                    "styles": {
                      "fill": "2:24"
                    },
                    "effects": [],
                    "characters": "Label",
                    "style": {
                      "fontFamily": "Manrope",
                      "fontPostScriptName": "Manrope-Semibold",
                      "fontWeight": 600,
                      "textAutoResize": "WIDTH_AND_HEIGHT",
                      "fontSize": 12,
                      "textAlignHorizontal": "CENTER",
                      "textAlignVertical": "TOP",
                      "letterSpacing": 0,
                      "lineHeightPx": 16,
                      "lineHeightPercent": 113.77777862548828,
                      "lineHeightPercentFontSize": 133.3333282470703,
                      "lineHeightUnit": "PIXELS"
                    },
                    "characterStyleOverrides": [],
                    "styleOverrideTable": {}
                  }
                ],
                "absoluteBoundingBox": {
                  "x": -331,
                  "y": -270,
                  "width": 65,
                  "height": 32
                },
                "constraints": {
                  "vertical": "TOP",
                  "horizontal": "LEFT"
                },
                "clipsContent": true,
                "background": [
                  {
                    "blendMode": "NORMAL",
                    "type": "SOLID",
                    "color": {
                      "r": 0.1921568661928177,
                      "g": 0.4941176474094391,
                      "b": 1,
                      "a": 1
                    }
                  }
                ],
                "fills": [
                  {
                    "blendMode": "NORMAL",
                    "type": "SOLID",
                    "color": {
                      "r": 0.1921568661928177,
                      "g": 0.4941176474094391,
                      "b": 1,
                      "a": 1
                    }
                  }
                ],
                "strokes": [],
                "cornerRadius": 4,
                "rectangleCornerRadii": [
                  4,
                  4,
                  4,
                  4
                ],
                "strokeWeight": 1,
                "strokeAlign": "INSIDE",
                "backgroundColor": {
                  "r": 0.1921568661928177,
                  "g": 0.4941176474094391,
                  "b": 1,
                  "a": 1
                },
                "styles": {
                  "fills": "2:23"
                },
                "layoutMode": "HORIZONTAL",
                "itemSpacing": 8,
                "counterAxisAlignItems": "CENTER",
                "primaryAxisAlignItems": "CENTER",
                "paddingLeft": 16,
                "paddingRight": 16,
                "paddingTop": 8,
                "paddingBottom": 8,
                "effects": []
              }
            ],
            "absoluteBoundingBox": {
              "x": -360,
              "y": -295,
              "width": 703,
              "height": 327
            },
            "constraints": {
              "vertical": "TOP",
              "horizontal": "LEFT"
            },
            "clipsContent": true,
            "background": [
              {
                "blendMode": "NORMAL",
                "type": "SOLID",
                "color": {
                  "r": 1,
                  "g": 1,
                  "b": 1,
                  "a": 1
                }
              }
            ],
            "fills": [
              {
                "blendMode": "NORMAL",
                "type": "SOLID",
                "color": {
                  "r": 1,
                  "g": 1,
                  "b": 1,
                  "a": 1
                }
              }
            ],
            "strokes": [],
            "strokeWeight": 1,
            "strokeAlign": "INSIDE",
            "backgroundColor": {
              "r": 1,
              "g": 1,
              "b": 1,
              "a": 1
            },
            "effects": []
          }
        ],
        "backgroundColor": {
          "r": 0.8980392217636108,
          "g": 0.8980392217636108,
          "b": 0.8980392217636108,
          "a": 1
        },
        "prototypeStartNodeID": null,
        "prototypeDevice": {
          "type": "NONE",
          "rotation": "NONE"
        }
      }
    ]
  },
  "components": {},
  "schemaVersion": 0,
  "styles": {
    "2:24": {
      "key": "78ed579c85888ec1f7dddc34a332411088a43de3",
      "name": "Neutral/100",
      "styleType": "FILL",
      "description": ""
    },
    "2:23": {
      "key": "5f59a662b7b9c044ae49c29ecd9b8548d3059d02",
      "name": "Light/Primary/500",
      "styleType": "FILL",
      "description": ""
    }
  },
  "name": "Tests intégration",
  "lastModified": "2021-07-29T20:44:52Z",
  "thumbnailUrl": "https://s3-alpha-sig.figma.com/thumbnails/220832be-80fb-4db5-9c4a-4cc345199494?Expires=1628467200&Signature=FFAaY2ECZpQEX7r43TiQgU1gk8~V16T6rQDGrp~m88tKPno1RvrofgBVFZufL1843AiTb6ldWG6t7SBdXU4PtGIVU5-5bV61ML6SVchrkla0zOWwOf20BQirPCAcKkmZZzeRZTf3brPCNKo6Gl5UTzARcjRod7UxtiYVcqCXp4bSPzBXxihnGBLNSnoZivfsIvXeIDXrwqFbEDPK3YuYK9KOuoA2Zrye3sCIVGViV6UQXTrUZkUxvkmECGLn9vKjHUBnNkqYGaV~8krw1dU1aHR2Za-Pn8xHUN2PljC2R1zGcFe0U5dESBx7vNw3HhAWM1uRIwYjys~kMTb7Y-qiRA__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA",
  "version": "1015012232",
  "role": "owner"
}
</details>
