### ISSUE TITLE
"No designs found" cannot get addon to display Figma

### ISSUE THREAD

**Issue by DannyAllegrezza** [pocka/storybook-addon-designs#117]
### Affected design types

- [X] figma
- [ ] experimental-figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

After installing the `storybook-addon-designs` package, the **Design** addon tab does not display the embedded Figma link. 

![Screen Shot 2021-08-04 at 4 37 27 PM](https://user-images.githubusercontent.com/7738918/128261757-6460a9df-c60d-423c-bf70-c4c51168f3f1.png)

### How to reproduce the bug?

Unfortunately my repo is private, but the steps I took were:

1. Run `npm install -D storybook-addon-designs`
2. Update `main.ts` (note: our `.ts` extension here), adding the `storybook-addon-designs` addon
```ts
export default {
  stories: [
    '..snip..'
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-a11y', 
    'storybook-addon-designs' 
  ],
```
3. Updated a Story

```tss
import { Story, Meta } from '@storybook/react/types-6-0';
import { withDesign} from 'storybook-addon-designs';
import ConversationIntro, { ConversationIntroProps } from '.';

export default {
  title: 'Title',
  component: ConversationIntro,
  decorators: [withDesign],
  args: {
    expectations:
      '....`,
  },

} as Meta;

const Template: Story<ConversationIntroProps> = (args) => (
  <ConversationIntro {...args} />
);

export const Default = Template.bind({});
Default.parameters = {
  type: 'figma',
  url: 'https://www.figma.com/file/our-file-here'
}

```

I have verified my Figma URL, and even tried to use the one in the docs (https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample) with no luck.

* There are no compilation errors. No errors in the console or at run time 🤔 

Any help would be appreciated. Thanks!

### Expected behaviour

The Figma file is displayed in the **Design** addon tab.

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.0.1

### Storybook versions

6.3.4

**Comment by pocka** [comment]
You forgot the `design` namespace for the parameter 😉 

```js
Default.parameters = {
  design: {
    type: 'figma',
    url: 'https://www.figma.com/file/our-file-here'
  }
}
```

**Comment by DannyAllegrezza** [comment]
Oh wow, that is embarrassing 😅  Adding the `design` key fixed my issue. 

Thank you, @pocka!
