### ISSUE TITLE
Warning - Importing from '@storybook/addon-docs/blocks' is deprecated - Storybook 6.3.7

### ISSUE THREAD

**Issue by icex** [pocka/storybook-addon-designs#120]
Hi,

I'm using your addon and getting this warning in  Storybook 6.3.7
``Importing from '@storybook/addon-docs/blocks' is deprecated, import directly from '@storybook/addon-docs' instead:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports``

https://github.com/pocka/storybook-addon-designs/blob/a29840d5edf0afc2f52a72945801c3aed7236842/packages/storybook-addon-designs/src/blocks.tsx#L3

Probably needs to be replaced with just @storybook/addon-docs

**Comment by pocka** [comment]
Due to the exports is only available from Storybook v6.3 and this addon supports `storybook >= 6.0`, I'll include the change in the next major version of this addon (`storybook-addon-designs@7.0`).

**Comment by pocka** [comment]
Fixed in v7.0.0-alpha.0.
