### ISSUE TITLE
Multiple experimental-figspec in same Story are not working as expected

### ISSUE THREAD

**Issue by sauldeleon** [pocka/storybook-addon-designs#122]
### Affected design types

- [ ] figma
- [X] experimental-figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

When adding multiple designs to the design parameter section, multiple `experimental-figspec` are not allowed, or only the first one will work.

### How to reproduce the bug?

Create a storybook and add the following configuration in the design section:

```js
 parameters: {
    design: [
      {
        name: 'Dropdown list design',
        type: 'experimental-figspec',
        accessToken: 'awesome-token',
        url: 'https://www.figma.com/blabblablabla,
      },
      {
        name: 'Dropdown button design',
        type: 'experimental-figspec',
        accessToken: 'awesome-token',
        url: 'https://www.figma.com/bleblebleble,
      },
    ],
  },
```

The first item in the array will work with the Figma spec, but the second figma design will have a strange behaviour, like being stuck.

Adding a fig-spec and a figma will work normally

```js
 parameters: {
    design: [
      {
        name: 'Dropdown list design',
        type: 'experimental-figspec',
        accessToken: 'awesome-token',
        url: 'https://www.figma.com/blabblablabla,
      },
      {
        name: 'Dropdown button design',
        type: 'Figma',
        url: 'https://www.figma.com/bleblebleble,
      },
    ],
  },
```

### Expected behaviour

I guess adding 2 figspecs experimental should work normally, changing the tab would set the iframe to the correct figma url allowing to play with the different Figma elements.

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.1.0

### Storybook versions

6.3.8

**Comment by pocka** [comment]
Fixed in v6.2.0
