### ISSUE TITLE
Does it support angular/clarity based projects 

### ISSUE THREAD

**Issue by Mrinmoy13** [pocka/storybook-addon-designs#129]
### Affected design types

- [X] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

Hi, while trying to integrate it in an angular/clarity-based project I am experiencing the issue, I don't see the design tab, I do understand that this addon is platform-agnostic but we are facing issues while integrating the same. Following the below documentation.

https://pocka.github.io/storybook-addon-designs/?path=/docs/docs-quick-start--page

My project specifications are given below :

"@storybook/angular": "^6.3.7",
"storybook-addon-designs": "^6.2.0",

main.js
"addons": [
'storybook-addon-designs',
"@storybook/addon-links",
"@storybook/addon-essentials",
'@storybook/addon-a11y',
],

any help would be greatly appreciated.

### How to reproduce the bug?

1. Opened official examples page to incorporate the design-addon

### Expected behaviour

Expecting the design tab to be available with a possible provided design link 

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

^6.2.0

### Storybook versions

^6.3.7

![image](https://user-images.githubusercontent.com/90275825/136571023-79b58039-23b6-4ad1-82a8-0784d4bbfd96.png)

**Comment by manuelmeister** [comment]
This looks like a bug not in this addon.
