### ISSUE TITLE
renderTarget: tab no longer works

### ISSUE THREAD

**Issue by sysofwan** [pocka/storybook-addon-designs#134]
### Describe the bug

Usage with tab rendering no longer works in the demo [here](https://pocka.github.io/storybook-addon-designs/tab/?path=/story/docs-figma-examples--embed-file).

I suspect this is caused by this [PR](https://github.com/pocka/storybook-addon-designs/pull/112). I think the tab addons does not support function titles.

### How to reproduce the bug?

1. Navigate to tab demo [here](https://pocka.github.io/storybook-addon-designs/tab/?path=/story/docs-figma-examples--embed-file).
2. Observe that design tab does not render.

### Expected behaviour

Design tab should render

### Affected versions

6.1.0

### Storybook versions

6.4.9

**Comment by pocka** [comment]
Thank you for reporting. I released [`storybook-addon-designs@v6.2.1`](https://github.com/pocka/storybook-addon-designs/releases/tag/v6.2.1), which includes a patch for the bug.

**Comment by sysofwan** [comment]
Thank you!

**Comment by Drakogangcom** [comment]
Slow

**Comment by ThomasCarca** [comment]
Hello this seems broken again in the latest version. We had to revert to v6.2.1 where it seems to work just fine.

**Comment by pocka** [comment]
Would you mind opening a new ticket?
