### ISSUE TITLE
Figma designs not clearing when changing between stories

### ISSUE THREAD

**Issue by rkara** [pocka/storybook-addon-designs#14]
Storybook for Angular
Version of `storybook-addon-designs`: 5.1.0

Setup:
* Have two stories
* Only one of the two stories has a design of type `figma`

Steps to reproduce within storybook
1. Navigate to story that has figma design and select "design" add-on tab to view design.
1. Navigate to story that does not have a design.
1. Notice that design from first story is still visible on the "design" add-on tab.

**Comment by pocka** [comment]
@rkara 
Thank you for reporting!

Fixed in [v5.1.1](https://github.com/pocka/storybook-addon-designs/releases/tag/v5.1.1)

**Comment by rkara** [comment]
@pocka 
No problem!  Thank you for the fast turnaround on this!
