### ISSUE TITLE
Is withDesign decorator necessary ?

### ISSUE THREAD

**Issue by Mattgic** [pocka/storybook-addon-designs#144]
Hello, quick question : Is `withDesign` decorator necessary ? It seems to work without it. As specified in documentation:
- I added 'storybook-addon-designs' in my addons array in my `main.js`
- Some of my stories have a parameter.design property in their export default

Design tab still appears on my stories — only those with parameters.design of course. 
This is more an unexpected behaviour than a bug, I just want to know if I can safely omit `withDesign` from my stories :simple_smile:

**Comment by SassNinja** [comment]
I was wondering "why do I have to import the decorator all the time" and can confirm it works without problem when I just omit it (using @storybook/vue3). Just like @Mattgic I've now got only the addon in my `main.js` and `parameters.design` in my story.

@pocka if you're unable to find a case where the decorator is necessary, it would definitely be a good idea to remove it (at least from the README) to avoid any confusion or rather unnecessary work.
