### ISSUE TITLE
Integration with Angular

### ISSUE THREAD

**Issue by mohammedhamza1** [pocka/storybook-addon-designs#152]
![image](https://user-images.githubusercontent.com/24924500/169608541-e1c57c40-55c3-404a-8d7f-20af1751b229.png)

**Comment by mohammedhamza1** [comment]
By doing this

![image](https://user-images.githubusercontent.com/24924500/169607466-abaf1f48-4090-4cdb-aa28-5fdc83dd88d2.png)

**Comment by pocka** [comment]
Please fill out the issue template or use discussion feature.
