### ISSUE TITLE
Retain loaded design tab contents per story

### ISSUE THREAD

**Issue by Philzen** [pocka/storybook-addon-designs#153]
### Opportunity

It's often frustrating when looking at the design tab, then switching to another tab (i.e. the controls tab to change some prop) and then returning to the design tab, only to find that the design being loaded all over again. Loading figma or figspec designs can take a considerable amount of time (~5 secs in average).

### Solution

Once loaded, the design tab content should be retained in memory, at least until the user navigates to another story in the left sidebar.

### Design types

- [x] `figma`
- [x] `figspec`
- [ ] `link`
- [x] `image`
- [x] `iframe`

**Comment by pocka** [comment]
Fixed in v7.0.0-alpha.1.

**Comment by Philzen** [comment]
Awesome, @pocka thanks heaps!
