### ISSUE TITLE
Sketch Workspace integration

### ISSUE THREAD

**Issue by gandradeglobal** [pocka/storybook-addon-designs#154]
I'm not sure why we're not able to use the iframe functionality to include components from sketch workspace, this would be an amazing feature to have.

As far as I understand they use oEmbed protocol, which works when embedding into Notion, so I don't understand why it can't be used here

**Comment by gandradeglobal** [comment]
I tried embedding something like this: https://www.sketch.com/s/8b86f24e-3ef5-4f67-b74b-6b102e05e226/a/R2QAyl#Inspect
And I can embed it into Notion as an example like so https://goncaloandrade.notion.site/Sketch-embed-example-34cdd7f5cb744f62a0df66d067eba7f9

However, if I try to include it into Storybook I get an error: https://629095abf15092004a4f6993-sfdbrlyrzn.chromatic.com/?path=/story/inputs-button--button-story

**Comment by pocka** [comment]
I couldn't find Sketch's oEmbed API endpoint (none of `https://www.sketch.com/api/oembed` `https://www.sketch.com/services/oembed` `https://www.sketch.com/oembed` worked). However, <https://www.sketch.com/embed/s/8b86f24e-3ef5-4f67-b74b-6b102e05e226/a/R2QAyl>, which is your first link but with an additional `/embed` at the root of the path, worked in an iframe. You can obtain the URL by adding `/embed` manually or [using iframely.com as the Sketch official docs describe](https://www.sketch.com/docs/sharing-and-permissions/sharing-documents/#embedding-documents-using-a-html-snippet).

I'm not sure there is a reliable way to programmatically obtain an embed URL from Sketch's share URL. It seems they have neither developer reference for embedding nor public oEmbed document.

**Comment by pocka** [comment]
v7.0.0-alpha.2
