### ISSUE TITLE
Sketch support

### ISSUE THREAD

**Issue by FRickReich** [pocka/storybook-addon-designs#158]
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

When i try to use sketch, like it was shown in your placeholder file, it tells me i have an incorect type. I am using the newest version of storybook-addon-designs.

### How to reproduce the bug?

```
design:
    {
        type: "sketch",
        url: "https://www.sketch.com/s/..."
    }
```

### Expected behaviour

I should be able to see the sketch.com design.

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

7.0.0-alpha.2

### Storybook versions

6.5.0

**Comment by pocka** [comment]
Which error message? If it was the `Invalid Sketch URL` one, a text below the title describes what's wrong with your URL.
