### ISSUE TITLE
Calling "copy" will crash at run-time because it's an import namespace object

### ISSUE THREAD

**Issue by yannbf** [pocka/storybook-addon-designs#161]
### Affected design types

- [X] figma
- [X] figspec
- [X] link
- [X] image
- [X] iframe

### Describe the bug

```sh
[WARNING] Calling "copy" will crash at run-time because it's an import namespace object, not a function [call-import-namespace]

    node_modules/@figspec/components/esm/es2015/FigspecViewer/InspectorView/InspectorView.js:62:42:
      62 │ ...yIcon({ onClick: () => copy(node.characters) })}
         ╵                           ~~~~

  Consider changing "copy" to a default import instead:

node_modules/@figspec/components/esm/es2015/FigspecViewer/InspectorView/InspectorView.js:2:7:
      2 │ import * as copy from "copy-to-clipboard";
        │        ~~~~~~~~~
        ╵        copy
```

### How to reproduce the bug?

1. Install Storybook 7.0.0-alpha (you can find an example [here](https://github.com/yannbf/mealdrop/tree/feat/sb-7.0))
2. Run `yarn storybook`
3. See the problem

### Expected behaviour

The addon executes correctly in Storybook 7.0

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.3.1 and 7.0.0-alpha.2

### Storybook versions

7.0.0-alpha.18

**Comment by yannbf** [comment]
Hey @pocka, I'm adding this issue just for reference so others can come here if they experience it, but it has been fixed already actually.

This issue happens in `@figspec/components@1.0.0`, but has been [fixed](https://github.com/pocka/figspec/pull/36) and released in `@figspec/components@1.0.1`, however when updating `storybook-addon-designs` from `6.3.1` to `7.0.0-alpha.2`, or really just staying at `6.3.1`, the transitive dependency did not update (respected my yarn.lock), and thus I had the issue.

So if anyone bumps into this issue in the future, the culprit might be your package.manager. The issue will cease to exist once your `@figspec/components` version is updated, and you can do so by:

1. Removing your lock file and reinstalling
2. Setting yarn resolutions / npm overrides

**Comment by pocka** [comment]
Thanks @yannbf , I'll update the `dependencies` section on `@figspec/*` side.
https://github.com/pocka/figspec-react/blob/4f28a4181907b152bc9232d74f8809a0eca44a59/package.json#L33

**Comment by pocka** [comment]
https://github.com/pocka/figspec-react/commit/c7137440e44e3891c585b5cd610a84b67a1234a8 ([`@figspec/react@v1.0.3`](https://github.com/pocka/figspec-react/blob/master/CHANGELOG.md#103---2022-10-16))
