### ISSUE TITLE
Default type works, but not quite

### ISSUE THREAD

**Issue by thany** [pocka/storybook-addon-designs#163]
### Affected design types

- [X] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

I'm putting a default `type: 'figma'` in our `preview.js` so that we don't have to put it in each and every story that is hooked up with a design. This makes sense, because we only ever use Figma.

However, this causes *every* story to show a `Design (1)` tab which injects an empty iframe (see picture). So it does "find" this `type` setting, as it turns out. Problem seems to be that this `type` setting is what dictates the tab being added.

![image](https://user-images.githubusercontent.com/152227/187947859-4ab1f000-3a68-4659-a1bd-24ba116de38d.png)

I'm not 100% sure if we should call this a bug, or a wish, or missing functionality or what-have-you. But I'm reporting it anyway, because to me it makes sense to put as much default stuff into `preview.js` as possible, so that stories can remain lean.

### How to reproduce the bug?

Add this to the `preview.js`:

```javascript
export const parameters = {
  // ...
  design: {
    // Default type, further specified in each applicable story
    type: 'figma',
  },
};
```

And then in each story:

```javascript
export default {
  title: 'Example/Button',
  // ...
  parameters: {
    design: {
      url: 'https://www.figma.com/file/LKQ4FJ4bTnCSjedbRpk931/Sample-File',
    },
  },
};
```

### Expected behaviour

When `parameters.design.url` is missing from a story, just show the default empty state on the `Design` tab (without the `(1)` suffix).

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [X] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.3.1

### Storybook versions

6.5.10

**Comment by pocka** [comment]
`type: "figma"` embed [fallbacks to a simple `iframe` embed with console warning if the config is invalid](https://github.com/pocka/storybook-addon-designs/blob/6222adfe91695065168345197dfd71f9188b0a3e/packages/storybook-addon-designs/src/register/components/Figma.tsx#L24-L27), so this behavior is intended. Probably setting `design: []` would stop the parameter merging behavior.

**Comment by thany** [comment]
Yes, that's exactly my point. That `The URL you specified is not valid Figma URL` isn't showing up. It loads an *empty* iframe.

I'm not sure where you want me to put `design: []`. I do like the default `type` to go somewhere...
