### ISSUE TITLE
No `type` crashes Storybook completely

### ISSUE THREAD

**Issue by thany** [pocka/storybook-addon-designs#164]
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

When not including the `type` property, it'll crash Storybook to a WSOD. On the console, it goes:
![image](https://user-images.githubusercontent.com/152227/187953797-55b87f18-c455-40c0-8176-6ee33541647f.png)

I was just testing what would happen if I leave it out. Since there is a mechanism in place for detecting erronous configuration, and showing a human-readable message on the `Design` tab, I was surprised not to see that message in this scenario. Perhaps reading the config should be written a bit more defensively.

### How to reproduce the bug?

Add parameters to a story like this:

```javascript
export default {
  title: 'Example/Button',
  // ...
  parameters: {
    design: {
      url: 'https://www.figma.com/file/LKQ4FJ4bTnCSjedbRpk931/Sample-File',
    },
  },
};
```

And refresh or run Storybook 😬

### Expected behaviour

Either:

1. It shows the same human-readable message you get when you include `type`, but omit `url`.
2. It autodetect from the `url` that it is unequivocally a Figma design.

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [X] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.3.1

### Storybook versions

6.5.10

**Comment by pocka** [comment]
https://github.com/pocka/storybook-addon-designs/blob/6222adfe91695065168345197dfd71f9188b0a3e/packages/storybook-addon-designs/src/register/components/Wrapper.tsx#L47

**Comment by thany** [comment]
Yes, that likely causes it.

So maybe it'll be as simple as `cfg.type?.toUpperCase()`.

**Comment by pocka** [comment]
[v7.0.0-beta.0](https://github.com/pocka/storybook-addon-designs/releases/tag/v7.0.0-beta.0)

I also added ErrorBoundary so that the rest of the Storybook UI survives when this addon crashed.
