### ISSUE TITLE
Update peerDependencies in v7

### ISSUE THREAD

**Issue by AE1NS** [pocka/storybook-addon-designs#175]
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

Inside /packages/storybook-addon-designs/package.json the storybook peerDependencies are still referenced as v6. 

### How to reproduce the bug?

Install package with storybook alpha packages.
Some "missing peer" errors occurs when using pnpm install.

### Expected behaviour

peerDepenendencies should be raised to storybook 7 to fix the errors.

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

7.0.0-beta.1

### Storybook versions

7.0.0-alpha.49

**Comment by pocka** [comment]
v7.0.0-beta.2

**Comment by bodograumann** [comment]
Unfortunately the range `^6.4.0 || ^7.0.0` does not include the prerelease versions.
I would have thought we should use `^6.4.0 || >=7.0.0-beta <7.0.0 || ^7.0.0`, but it seems that might not work either according the the calculator: https://semver.npmjs.com/
Maybe we could exclude v6 and use `>=7.0.0-beta <7.0.0 || ^7.0.0`?

**Comment by pocka** [comment]
No plan to support unstable releases. Use dependency resolutions if you want suppress warnings.
