### ISSUE TITLE
publish latest docs to NPM

### ISSUE THREAD

**Issue by olets** [pocka/storybook-addon-designs#182]
**Is your feature request related to a problem? Please describe.**

The docs in the version published to https://www.npmjs.com/package/storybook-addon-designs are outdated. Notably they're missing the 7 beta install instructions, and they have `withDesign` being needed.

**Describe the solution you'd like**

Publish the latest to NPM

**Describe alternatives you've considered**

**Design types**

- [ ] `figma`
- [ ] `figspec`
- [ ] `link`
- [ ] `image`
- [ ] `iframe`

**Additional context**

**Comment by pocka** [comment]
See https://www.npmjs.com/package/storybook-addon-designs/v/7.0.0-beta.2

npm shows the latest stable version (v6.3.1 at the time of writing), which is not compatible with Storybook v7.

**Comment by olets** [comment]
Cool. I could have been more specific: the difference between 6.3.1's readme and `main`'s readme, especially https://github.com/pocka/storybook-addon-designs/commit/1eefd7a997e27415d31523335930716bc2d0ac4b being unreleased, means the instructions on NPM are wrong. I landed on NPM before GitHub (don't remember if it was higher in search or if Storybook docs linked me to it), and others might too. Not arguing though, just clarifying.
