### ISSUE TITLE
Figma login error

### ISSUE THREAD

**Issue by onursabanoglu** [pocka/storybook-addon-designs#184]
### Affected design types

- [x] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

I added my parameter in the component, but it asks me to login to figma, I can login successfully, but there is no change, after refreshing it asks me to login again. Any ideas where am I going wrong?

**My parameter**

```example.stories.js
Default.parameters = {
  design: {
    type: 'figma',
    url: 'https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample'
  }
}
```

**Screen**
![Screen Shot 2023-02-22 at 3 38 42 PM](https://user-images.githubusercontent.com/47773417/220622526-e12481df-5607-4776-9bce-bc510372651f.png)

### How to reproduce the bug?

.

### Expected behaviour

Opening the figma file on the storybook side after logging in.

### Environment

- [x] Chrome / Chromium / Chromium based browsers
- [x] Firefox
- [x] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.3.1

### Storybook versions

6.5.16

**Comment by judithrocketmakers** [comment]
Can confirm it's not just you - just in case it makes a difference, I normally sign in via org-linked login rather than a straight password, but I would guess the same auth flow applies to both?

**Comment by EvanSays** [comment]
I had this problem and resolved it by turning off the ad blocker in my browser. Try that if ya can.

**Comment by onursabanoglu** [comment]
This way worked. Thank you 🙏

**Comment by pocka** [comment]
Related: #96 

https://github.com/pocka/storybook-addon-designs/commit/cb14774b3070958ca387f8325e182f1338e276c8
https://pocka.github.io/storybook-addon-designs/?path=/story/docs-figma-readme--page
