### ISSUE TITLE
Add instructions for Storybook 5.2

### ISSUE THREAD

**Issue by ben-rogerson** [pocka/storybook-addon-designs#21]
I'm having trouble getting this plugin to work in the new "component-story-format" (CSF).

For example:
```js
simple.story = {
    name: 'default',
    decorators: [
        storyFn => <div style={{ border: '5px solid red' }}>{storyFn()}</div>
    ]
};
```
 
Is it possible to declare the decorator in this way?

More info: https://storybook.js.org/docs/formats/component-story-format/#story-exports

**Comment by aterris** [comment]
I was also looking at using this with the CSF syntax and I believe this should work for you.  Would be great to get this added to the documentation, but not sure yet if/when I will have time to submit a PR.

But, to hopefully get you moving, here is what seems to be working for me.

````
import { withDesign } from 'storybook-addon-designs'

export const simple = () => <MyComponent prop1={val1} />;

simple.story = {
  name: 'simple name',
  decorators: [withDesign],
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/your_url'
    }
  }
};
````

**Comment by ben-rogerson** [comment]
hey Andrew, thanks so much for the code - I've now got it working perfectly 👍

**Comment by ben-rogerson** [comment]
ps: If you're too busy for a PR, let me know and I'll tackle it
