### ISSUE TITLE
SyntaxError: invalid regexp group

### ISSUE THREAD

**Issue by michelcve** [pocka/storybook-addon-designs#25]
When I install your addon, I get the following error in the console: "SyntaxError: invalid regexp group"

Same thing happens with our own demo: http://bestof.morganatwork.com/storybook-addon-xd-designs/

**Comment by pocka** [comment]
@michelcve 
I opened your link with Chrome 78.0 (Chrome OS) but couldn't see the error.
Can you provide your browser information and an error log or screenshot?

**Comment by michelcve** [comment]
Here you go:

![afbeelding](https://user-images.githubusercontent.com/13715834/71367633-f0eb3780-25a5-11ea-8ce5-b4a1b4fabfdc.png)

I was using the latest firefox:

![afbeelding](https://user-images.githubusercontent.com/13715834/71367675-0e200600-25a6-11ea-8abd-826212e98a38.png)

**Comment by michelcve** [comment]
In Chrome it work, though I do see some warnings:

![afbeelding](https://user-images.githubusercontent.com/13715834/71367813-6b1bbc00-25a6-11ea-99f8-08eaf9966b63.png)

**Comment by pocka** [comment]
Oh, what you're using is [storybook-addon-xd-designs](https://github.com/morgs32/storybook-addon-xd-designs), not this addon. Please file an issue there.

**Comment by michelcve** [comment]
Wow, I feel stupid now, sorry :-)
