### ISSUE TITLE
ES5 Support

### ISSUE THREAD

**Issue by hbk619** [pocka/storybook-addon-designs#28]
Currently this project targets ES2015 which doesn't run in IE11, I have to support IE11 and being able to run Storybook inside that would be really helpful! Is this something you'd be open to doing? It's a simple change to tsconfig.json to:

"target": "ES5"

but I realise it adds more testing burden on to the project. What do you think?

**Comment by pocka** [comment]
I have no plan to support ES5. You can configure webpack to transpile this package for IE11.

```js
{
  test: /\.js$/,
  include: /node_modules\/storybook-addon-designs\//,
  use: ['babel-loader']
}
```

If there is a high demand for ES5 support, I'll add a bundle for it (like `storybook-addon-desgins/es5`).

**Comment by hbk619** [comment]
It's not possible to modify the main storybook webpack config, the iframe you can (and I have as we have another dependency that uses ES6) but addons get included by the parent (manager) app which has it's own config.

No problem though, I understand, thanks for the quick response.

**Comment by pocka** [comment]
You can customize manager webpack config with a custom preset (though it's a workaround).

https://github.com/storybookjs/storybook/issues/4995

**Comment by hbk619** [comment]
Didn't see that, will give it a go, thanks!

**Comment by deviantpixel** [comment]
@pocka I'm having the same issue (trying to get this working in IE11) and have tried the following:

Edited .storybook/main.js
`
module.exports = {
  managerWebpack: async (config, options) => {
    config.module.rules.push({
      test: /\.js$/,
      include: /node_modules\/storybook-addon-designs\//,
      use: ['babel-loader']
    });
    return config;
  }
};
`

Is that correct? It doesn't seem to have an effect on the code that I see inside the main...bundle.js combined file. Can you provide any more direction?

**Comment by Smolations** [comment]
Just to chiming in here as I am following the related issue in the storybook project, but it seems like poor design to me to create an addon for a library which supports IE11 and not make sure the addon shares that support. I have run into this issue with another addon and that maintainer was willing to update their package.

@pocka Can you expound on why you are unwilling to update your (default) build config to support es5? This seems pretty standard for all libs as the webpack recommendation for `babel-loader` is to exclude node modules. I have only been running into this conflict with storybook addons.

All that to say, I am upvoting the idea of adding an additional es5 bundle (though I would much prefer the default build to be transpiled to es5).

👍

**Comment by pocka** [comment]
~I'll add an optional es5 bundle or an addon preset options for this in v5.3.~

I'll change the default bundle to ES5 (read below for the reason) in v5.3 or v5.2.x.

---

@Smolations 
> but it seems like poor design to me to create an addon for a library which supports IE11 and not make sure the addon shares that support.

~I don't think so unless it's an official addon (`@storybook/***`) or the library defines addon/plugin guidelines.~

I wondered are there any guidelines and read an official Storybook page again, then noticed there is a guideline for packaging :open_mouth: 
https://storybook.js.org/docs/addons/writing-addons/#package-maintenance

<details>
<summary>Reasons for ES2015 bundle (and some error correction)</summary>

> Can you expound on why you are unwilling to update your (default) build config to support es5?

Using ES5 in a library code comes with several downsides:

- Forcing unnecessary codes for most of the end-users (= increasing in bundle size), which library users can't get rid of.
- Need to care about the library's dependencies to support ES5 too, or to handle an issue claiming one of the dependencies does not work well at ES5 environment. (though this is rare)
- Need to care about WebAPIs either. e.g., Intersection Observer API.

The multiple bundle method solves the first one.

> This seems pretty standard for all libs as the webpack recommendation for babel-loader is to exclude node modules.

I'm not sure what "all libs" means, but there are not so few for-browser-libraries emitting ES2015 or later on NPM (for example, [Polymer](https://polymer-library.polymer-project.org/3.0/docs/es6) community uses ES2015 for their bundle). IIRC webpack recommends excluding `node_modules` for compilation times; it's not uncommon to exclude `node_modules` except some non-ES5 deps.

</details>

**Comment by deviantpixel** [comment]
You are awesome. Thanks so much for your work here :)
