### ISSUE TITLE
[Feature request] Link type

### ISSUE THREAD

**Issue by Romanchuk** [pocka/storybook-addon-designs#31]
Hello! First of all thank you for this addon, it's awesome!

Some websites can't be embeded as iframe (Cloud Confluence, notion.so) because of:

> content-security-policy: frame-ancestors 'self'

And you can't change headers to fix it. There is option to proxy, but it's too challenging (mostly because of Auth).

There is an idea to add **link type**, that would open design link in a new tab.

**Comment by pocka** [comment]
Implemented in [v5.2.0](https://github.com/pocka/storybook-addon-designs/releases/tag/v5.2.0).
