### ISSUE TITLE
Adobe XD support

### ISSUE THREAD

**Issue by bke-daniel** [pocka/storybook-addon-designs#34]
Hello team!
First of all: Great work, thank you!

Would you be interested in supporting Adobe XD. A workaround with `type: 'iframe'` isn't possible because if I'm doing the following
```
design: {
  type: 'iframe',
  url: 'https//my-url.com/uuid/',
},
``` 
the iFrame container states: "xd.adobe.com refused the connection"

Cheers
Daniel

**Comment by pocka** [comment]
@bke-daniel 
To embed your XD files, you need to obtain an embed link. I think [this tweet](https://twitter.com/elainecchao/status/752566904980582400) would help (Unfortunately, I couldn't find an official document or guides about that.)

The embed link is something looks similar to `https://xd.adobe.com/embed/...`

**Comment by shilman** [comment]
cc @tripodsan

**Comment by pocka** [comment]
> Would you be interested in supporting Adobe XD.

Oops, I missed this line :(
I don't have a plan for it now, but I'll add the feature if some amount of users want the feature.

If anyone interested in or wanting the feature, creating PR is the fastest way. I think [the one for Figma embed](https://github.com/pocka/storybook-addon-designs/blob/v5.2.0/packages/storybook-addon-designs/src/register/components/Figma.tsx) would help you.

**Comment by morgs32** [comment]
@bke-daniel well I forked pocka's a while ago to make this one for XD: https://github.com/morgs32/storybook-addon-xd-designs

**Comment by morgs32** [comment]
I suppose I should make a PR and find a way to merge the configs together

**Comment by pocka** [comment]
Added a link to the storybook-addon-xd-designs so users can find out easily. (abf8a4490605f42d7a436086a74aaad0f344d786)

**Comment by pocka** [comment]
Closing this issue as:

- there is a fork of the addon (https://github.com/morgs32/storybook-addon-xd-designs)
- Adobe provides neither a stable API (URL) nor official docs
- XD's embedding UX is horrible (even no zooming) IMO

the second one is critical and drained my motivation.

If anyone wants this feature, please create a Pull Request.

**Comment by pocka** [comment]
If you wanna embed XD files with this addon anyway, you can use the `iframe` embed type.

1. Obtain a URL by following [these instructions](https://github.com/morgs32/storybook-addon-xd-designs#how-to-make-and-find-your-spec-url)
2. Replace `https://xd.adobe.com/view` with `https://xd.adobe.com/embed`
3. Paste it to the `url` property

**Comment by morgs32** [comment]
> - Adobe provides neither a stable API (URL) nor official docs
> - XD's embedding UX is horrible (even no zooming) IMO

So true.
