### ISSUE TITLE
Releasing private figma support

### ISSUE THREAD

**Issue by hannahjin** [pocka/storybook-addon-designs#38]
Hi! I see that you recently added private figma support. I am really excited about this feature. I was trying to set it up today in my project only to realize that it hasn't been released yet. Since this is monorepo, I am unable to yarn install the latest using git reference. I was wondering if you have a timeline in mind when you will release it. Thank you!

**Comment by pocka** [comment]
I've just released `v5.3.0-alpha.0`, which includes private Figma file support. You can install it by `yarn add -D storybook-addon-designs@alpha`.

**Comment by hannahjin** [comment]
Thank you!

**Comment by pocka** [comment]
Hi all,

Figma announced [an official private embeds](https://www.figma.com/blog/announcing-live-figma-embeds/)! So you no longer need to include a token to use API in JavaScript code 🔒 

I'll remove the experimental private embeds support that was introduced in `v5.3.0-alpha.0` by stable release. If you're using that one, please switch to official private embeds.

To embed a private file is now super easy: copy-and-paste an URL of your Figma file (or Frame), just same as for public files. Figma app inside `<iframe>` automatically detects whether it's a private then show users a sign-in UI if needed.

I tested the feature at this repo's example with my private files and confirmed it works as intended. If you encountered a bug, please create a new issue with clear title and description (e.g. "Figma private embeds' sign-in button doesn't work").
