### ISSUE TITLE
Multiple Figma file zoom bug

### ISSUE THREAD

**Issue by withinsight** [pocka/storybook-addon-designs#39]
When using the "Multiple designs for single story" to load 2 Figma URLs, the 2nd tab loads with the zoom level so small as to appear blank.

The first tab renders the Figma asset at a reasonable size (fits design within the given frame), but the 2nd tab (perhaps because its not displayed and Figma does some type of size calculation when it loads to attempt to size correctly), when the user selects the 2nd tab it gives the user the impression its blank, and only when you click the zoom "+" icon multiple times does the design start to appear and increase in size.

**Comment by pocka** [comment]
Fixed in v5.3.0-alpha.1.
