### ISSUE TITLE
Undeclared peer-dependency seems to break storybook build under yarn2 

### ISSUE THREAD

**Issue by DimitrK** [pocka/storybook-addon-designs#41]
Seems like this is caused due to some internal use of `react-pdf` on `storybook-addon-designs`
Tried it with Yarn 2 &  Storybook `5.2.8` & `6.0.0-alpha.33`

If I had to guess I would blame this line: https://github.com/pocka/storybook-addon-designs/blob/9ed436e3e222e3fddbf016d2f0a9135efafb1ebe/packages/storybook-addon-designs/src/register/components/Pdf.tsx#L13

Stacktrace bellow 
```
ERROR in ~/.yarn/$$virtual/react-pdf-virtual-80afc2509e/0/cache/react-pdf-npm-4.1.0-5b5a86f6e3-2.zip/node_modules/react-pdf/dist/entry.webpack.js
Module not found: Error: @storybook/core tried to access worker-loader, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: worker-loader (via "worker-loader")
Required by: @storybook/core@virtual:02badcd84a8115c2d5f73b510f9f022dfca8ce2433db4223310d52c2dc4bbb61fdcf9d2d91c67a3cdaf5123d38a8be4e94605e12dab88fa9de236a0aea6d72ee#npm:6.0.0-alpha.33 (via ~/.yarn/$$virtual/@storybook-core-virtual-a55db608df/0/cache/@storybook-core-npm-6.0.0-alpha.33-85dfb5f3b0-2.zip/node_modules/@storybook/core/)

 @ ~/.yarn/$$virtual/react-pdf-virtual-80afc2509e/0/cache/react-pdf-npm-4.1.0-5b5a86f6e3-2.zip/node_modules/react-pdf/dist/entry.webpack.js 41:45-91
 @ ~/.yarn/$$virtual/storybook-addon-designs-virtual-8693906dc4/0/cache/storybook-addon-designs-npm-5.1.1-c1c64c5fd0-2.zip/node_modules/storybook-addon-designs/lib/register/components/Pdf.js
 @ ~/.yarn/$$virtual/storybook-addon-designs-virtual-8693906dc4/0/cache/storybook-addon-designs-npm-5.1.1-c1c64c5fd0-2.zip/node_modules/storybook-addon-designs/lib/register/components/Wrapper.js
 @ ~/.yarn/$$virtual/storybook-addon-designs-virtual-8693906dc4/0/cache/storybook-addon-designs-npm-5.1.1-c1c64c5fd0-2.zip/node_modules/storybook-addon-designs/lib/register/index.js
 @ ~/.yarn/$$virtual/storybook-addon-designs-virtual-8693906dc4/0/cache/storybook-addon-designs-npm-5.1.1-c1c64c5fd0-2.zip/node_modules/storybook-addon-designs/register.js
 @ ./.storybook/addons.js
 @ multi ~/.yarn/$$virtual/@storybook-core-virtual-a55db608df/0/cache/@storybook-core-npm-6.0.0-alpha.33-85dfb5f3b0-2.zip/node_modules/@storybook/core/dist/server/common/polyfills.js ~/.yarn/$$virtual/@storybook-core-virtual-a55db608df/0/cache/@storybook-core-npm-6.0.0-alpha.33-85dfb5f3b0-2.zip/node_modules/@storybook/core/dist/client/manager/index.js ./.storybook/addons.js
```

**Comment by pocka** [comment]
As the error itself describes, it comes from `@storybook/core` or `react-pdf`, not from this addon. A workaround for this is adding dependencies as the error message says (shout out to [this comment](https://github.com/styled-components/styled-components/issues/3082#issuecomment-606641463)):

```yaml
# .yarnrc.yml
packageExtensions:
  "pdfjs-dist@*":
    dependencies:
      "@babel/runtime": "*"
  "@storybook/core@*":
    dependencies:
      "worker-loader": "*"
```

NOTE1: `pdfjs-dist > @babel/runtime` thing is also required because `react-pdf` relies on old `pdfjs-dist` and it have a ambiguous import to `@babel/runtime`.
NOTE2: I don't know why Yarn says `@storybook/core` tried to access, instead of `react-pdf`.

Storybook does not support Yarn 2 (PnP) yet. They are implementing support for it in v6 but it's still alpha so I don't recommend using it in production.

**Comment by pocka** [comment]
After some thought, I decided to move these dependencies (such as `react-pdf`) to `optionalDependencies` in the next major version.

**Comment by DimitrK** [comment]
Thank you for your reply and for the steps you are taking moving forward. I reported this once I pinpointed the problem to this specific addon. Removing the addon from Storybook fixes the issue. I could try to create a minimal reproduction repo if you like
