### ISSUE TITLE
master branch should point to latest release (not alpha/beta/rc)

### ISSUE THREAD

**Issue by pocka** [pocka/storybook-addon-designs#44]
At the time of writing, the `master` branch is pointing at v5.3.0-alpha. I guess many JS devs read GitHub's README instead of one at npm. So, these users tried to install the `latest` tag then set it up with a Preset-way (not `storybook-addon-designs/register`), which is added in v5.3.0-alpha.

Storybook repo uses the `next` branch for pre-preases, so we should follow this strategy for easy understanding.

**Comment by shilman** [comment]
I'm not sure I understand the problem. The preset-style registration should is available in both 5.3/`master` and 6.0-alpha/`next`

**Comment by pocka** [comment]
@shilman `storybook-addon-designs@5.2.0` or earlier does not have `preset.js` file, so I think preset-style registration does not work (Storybook cannot find `storybook-addon-designs/preset.js`). Isn't that correct?

**Comment by pocka** [comment]
Now, the `master` branch points to a current stable release, and `v5.3.0` branch points to `v5.3.0*` releases.
