### ISSUE TITLE
Display specific component

### ISSUE THREAD

**Issue by elie222** [pocka/storybook-addon-designs#45]
We have a single artboard with lots of symbols/components on it. When I select the component and copy the link into storybook as the url with type `figma` it shows me the entire artboard.

Is there a way to only display the selected component or I have to move it into its own artboard to do that?

**Comment by pocka** [comment]
@elie222 
In Figma, you can copy the link for *files* and *frames* (think this as top-level objects). So if you want to embed a component belongs to a frame, you need to make it as a frame.

- [When to use groups versus frames in Figma (figma.com)](https://www.figma.com/best-practices/groups-versus-frames/frames/)

Unfortunately, it seems there is no way to embed a specific non-frame object (in other words, an object inside a frame).
