### ISSUE TITLE
figma decorator for all stories

### ISSUE THREAD

**Issue by landsman** [pocka/storybook-addon-designs#46]
I would love to setup one design for all stories via decorator in `config.js`.
This is working for me:

```
import { addDecorator, addParameters } from "@storybook/react";

// design
addDecorator(withDesign);
addParameters({
    design: {
        type: 'figma',
        url: 'https://www.figma.com/file/LKQ4FJ4bTnCSjedbRpk931/Sample-File'
    }
});
```

Can I send PR with updated README about this?

**Comment by pocka** [comment]
Of course, contributions are very welcome!

FYI, there is a PR to create docs to cleanup README (#37 ), so I'll move usage stuff from README to docs page. If you want to add the section to the new docs page, please send PR against `feature/docs` branch.

**Comment by pocka** [comment]
Detailed documentation is added in #53 and I put [a paragraph mentioning decorators and parameters](https://storybook-addon-designs-git-feature-docs.pocka.now.sh/?path=/story/docs-quick-start--page) there.
