### ISSUE TITLE
Example page doesn't seem to load Figma file

### ISSUE THREAD

**Issue by cailborg** [pocka/storybook-addon-designs#56]
When I click on the Figma embed examples, nothing loads
https://pocka.github.io/storybook-addon-designs/?path=/story/examples-figma--embed-file

**Comment by pocka** [comment]
It's working on Chrome 81.0.4044.141 (Chrome OS).

![pocka github io_storybook-addon-designs__path=_story_examples-figma--embed-file](https://user-images.githubusercontent.com/13316015/83217486-d8abc400-a1a6-11ea-8051-a4b8b9aa5203.png)

- Only the addon panel does not work or entire page is blank?
- What browser are you using?
- Any console errors?

**Comment by cailborg** [comment]
Just tried it in a Chrome incognito window and it worked fine, how weird.

FYI it was just the addon panel, just got a "loading..." message that never resolved

**Comment by pocka** [comment]
Probably it was a cache or session-related problem. Figma recently updated their Live Embed Kit (contents of iframes), so that could cause cache inconsistency or something else... Anyway, I'm glad to hear it's working now 😋
