### ISSUE TITLE
Allow to be registered as panel or tab

### ISSUE THREAD

**Issue by dhruvkb** [pocka/storybook-addon-designs#59]
Some Storybook addons like `addon-notes` can be registered as a panel (appear below the story, current behaviour of this addon) or as a tab (appear alongside 'Canvas', 'Docs' etc.). Can this addon also support registration as a tab?

**References:**
- [Getting Started for `addon-docs`](https://www.npmjs.com/package/@storybook/addon-notes#getting-started)
- [Tab registration](https://github.com/storybookjs/storybook/blob/master/addons/notes/register.js)
- [Panel registration](https://github.com/storybookjs/storybook/blob/master/addons/notes/register-panel.js)

**Comment by pocka** [comment]
#47 (v5.3.0-beta)
