### ISSUE TITLE
Doc Blocks

### ISSUE THREAD

**Issue by pocka** [pocka/storybook-addon-designs#61]
It would be good if the addon provides Doc Blocks (easy-to-use React components for Addon Docs). That enables users to embed design specs in their Docs and to build Storybook with Docs mode only.

```mdx
import { Meta, Story, Preview } from '@storybook/addon-docs/blocks';
import { Figma  } from 'storybook-addon-designs/blocks'
import { Button } from './Button';
 
<Meta title="MDX/Button" component={Button} />
 
# Checkbox
 
A basic button for everything.
 
<Preview>
  <Story name="basic-button">
    <Button>Button</Button>
  </Story>
</Preview>

<Figma url="https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample" />
```

Also, if possible, tabbed-preview would useful.

```jsx
import { PreviewWithDesign } from 'storybook-addon-designs/blocks'

<PreviewWithDesign
  design={{
    type: 'figma',
    url: 'https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample'
  }}
>
  <Story name="basic-button">
    <Button>Button</Button>
  </Story>
</PreviewWithDesign>

// or ...
import { Tabs, Tab } from 'storybook-addon-designs/blocks' // these are re-exports with small modification of ones in @storybook/components

<Tabs>
  <Tab title="Preview">
    <Preview>
      <Story name="basic-button">
        <Button>Button</Button>
      </Story>
    </Preview>
  </Tab>
  <Tab title="Design spec">
    <Figma url="https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample" />
  </Tab>
</Tabs>
```

**Comment by shilman** [comment]
This would be awesome! Currently Story blocks only get recognized under Preview blocks specifically, so we’d need to fix that for that part of your proposal to work. But having a Figma block would be amazing. How quickly could you turn that around? I want to do a post promoting DocBlocks as part of the 6.0 release, and would love to include that.

**Comment by pocka** [comment]
>  Currently Story blocks only get recognized under Preview blocks specifically, so we’d need to fix that for that part of your proposal to work.

I think it's not such problematic, just designing Blocks to keep `<Preview><Story>` structure would be enough IMO.

```jsx
// something like this?
<WithDesign figma="https://www.figma.com/file/Klm6pxIZSaJFiOMX5FpTul9F/storybook-addon-designs-sample">
  <Preview>
    <Story>
      <Button>Button</Button>
    </Story>
  </Preview>
</WithDesign>
```

If everything goes well, especially the theming and styling stuff, I can release (alpha, beta, or stable IDK) this feature within a week.

**Comment by shilman** [comment]
No. Story needs to be either at the top level or directly below Preview at the top level. It’s kind of an arbitrary requirement... nothing fundamental. But would require a chance to Storybook to support your proposal. Maybe start with the Figma and other standalone blocks and do the composite ones in SB 6.1?

**Comment by shilman** [comment]
If you just want to annotate `Story` with design info you can use parameters:

`<Story name=“foo” parameters={{ design: { ... }}}>...</Story>`

**Comment by pocka** [comment]
> No. Story needs to be either at the top level or directly below Preview at the top level. It’s kind of an arbitrary requirement... nothing fundamental. But would require a chance to Storybook to support your proposal. Maybe start with the Figma and other standalone blocks and do the composite ones in SB 6.1?

Oh... so is it better to ship only embed components (e.g. `<Figma>`, `<Pdf>`) and defer the tabbed-preview feature? TBH, the tabbed-preview feature is just an early idea and I'm not sure whether that is needed... Supporting non-top-level `<Preview>` sounds good but it will bring complexity in story parsing, so discussing carefully after a user submits a feature request is okay and keeps things simple 👍
