### ISSUE TITLE
Docs Blocks is not working

### ISSUE THREAD

**Issue by joshjeong** [pocka/storybook-addon-designs#64]
Receiving an "Unable to resolve path to module", when attempting to:
```import { Figma, IFrame } from 'storybook-addon-designs/blocks'```

From a quick glance, blocks is missing from package.json

Temporarily changing the import to ```'storybook-addon-designs/esm/blocks'``` works locally but fails when exporting static build

https://github.com/pocka/storybook-addon-designs/pull/62

**Comment by pocka** [comment]
Fixed in [v5.4.1](https://github.com/pocka/storybook-addon-designs/blob/master/CHANGELOG.md#541---2020-07-31).

- Commit: 9c74b7cf12dd7057bbb3ece328aea8ee9bead3fd
- [Working example on CodeSandbox](https://codesandbox.io/s/storybook-addon-desings-64-u65ow?file=/src/test.stories.mdx)
