### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by azeez1989** [pocka/storybook-addon-designs#72]
I am getting the following error when I try to configure figma with storybook- react.

ERROR in ./node_modules/storybook-addon-designs/node_modules/react-pdf/dist/pdf.worker.entry.js (./node_modules/storybook-addon-designs/node_modules/worker-loader/dist/cjs.js!./node_modules/storybook-addon-designs/node_modules/react-pdf/dist/pdf.worker.entry.js)
Module build failed (from ./node_modules/storybook-addon-designs/node_modules/worker-loader/dist/cjs.js):
TypeError: The 'compilation' argument must be an instance of Compilation

Can someone please help?

**Comment by pocka** [comment]
It's hard to diagnose errors related to the worker script (`react-pdf/dist/pdf.worker.entry.js`)...

[An error with the same message](https://github.com/jantimon/html-webpack-plugin/issues/1451) has reported on `html-webpack-plugin` and that might help you. If your lockfile has multiple webpack versions, it might be the root cause.

I'll release `storybook-addon-designs@6.0.0-alpha`, which drops `react-pdf` from our dependencies, until the end of this year (Sorry,  I'm a bit busy now...)

**Comment by dunklesToast** [comment]
Had the same issue and the problem were mulitple Webpack Versions (4.x and 5x). You should check that via `yarn why webpack` and should just use one version (probably 4.44.2) or so

**Comment by kiily** [comment]
Hi, I just tried installing the addon and following the setup for the new storybook (6+) syntax. Everything seems to build fine but I do not see a design tab in my stories. Tried added params globally and to specific stories and did the same with the decorator. 

I have no log either of any sort of error which is not helpful. @pocka how could I setup the repo and try to debug on my side?

**Comment by pocka** [comment]
@kiily 
This issue is for a webpack config bug (probably) caused by multiple webpack installations and worker-loader.

I believe this could help: https://github.com/pocka/storybook-addon-designs/issues/43

**Comment by kiily** [comment]
Strange, for me what fixed it was reverting to the old syntax in `main.js`. Passing the following string `'storybook-addon-designs/register'` immediately resulted in a working story

**Comment by xxc12138** [comment]
I also have this problem,but it is happen when I use VueLoaderPlugin,but it is necessary for me to use VueLoaderPlugin in my project;

**Comment by pocka** [comment]
If you face this error, please make sure you don't include multiple webpack versions in your project.

FYI, I published [`storybook-addon-designs@v6.0.0-alpha.0`](https://www.npmjs.com/package/storybook-addon-designs/v/6.0.0-alpha.0) that drops the PDF preview feature.
