### ISSUE TITLE
allowFullscreen in Figma behaves unpredictably

### ISSUE THREAD

**Issue by henrycity** [pocka/storybook-addon-designs#77]
**Bug**
- Description: When embedding Figma designs, story without `allowFullscreen` affects story with `allowFullscreen: true`. 
- Versions: 5.4.2
- Reproduction:
 a. Go to story with  `allowFullscreen: false` first
  1. Go to a page without `allowFullscreen`: https://pocka.github.io/storybook-addon-designs/?path=/story/docs-figma-examples--embed-file
  2. Go to a page with `allowFullsreen: true`: https://pocka.github.io/storybook-addon-designs/?path=/story/docs-figma-examples--allow-fullscreen. There is no option to the view Figma design in fullscreen, which there should be.
  
  b. Go to story with  `allowFullscreen: true` first
  1. Go to a page with `allowFullscreen: true`: https://pocka.github.io/storybook-addon-designs/?path=/story/docs-figma-examples--allow-fullscreen.
  2. Go to a page without `allowFullscreen`: https://pocka.github.io/storybook-addon-designs/?path=/story/docs-figma-examples--embed-file. There is an option to the view Figma design in fullscreen, which there shouldn't be.

**Comment by pocka** [comment]
Thank you for the detailed report even without an issue template (sorry for that I'm a too lazy man :pig2:)!

It seems that the preview component not refreshing properly. I'd like to ship the patch for this in the next patch release.

**Comment by henrycity** [comment]
> Thank you for the detailed report even without an issue template (sorry for that I'm a too lazy man 🐖)!
> 
> It seems that the preview component not refreshing properly. I'd like to ship the patch for this in the next patch release.

Great to hear and thank you. I would like to give as much information as possible so we will get things done faster! 😃

**Comment by pocka** [comment]
Fixed in [v5.4.3](https://github.com/pocka/storybook-addon-designs/releases/tag/v5.4.3).
