### ISSUE TITLE
Allow private figma integration

### ISSUE THREAD

**Issue by lulul62** [pocka/storybook-addon-designs#8]
Hi, 

First thank you for this plugin

i want to know if there is some possibility to add integration for private figma ? 

Thank ya

**Comment by pocka** [comment]
@lulul62 
Sorry, since I have no private files on Figma, I couldn't test that case.
Have you encountered any problems when trying it?

**Comment by pocka** [comment]
I encountered the problem: the private files, which disabled "public link access", cannot embed via iframe.

**Comment by superMDguy** [comment]
For anyone else who comes across this, I ended up using [storybook-figma-addon](https://github.com/dreipol/storybook-figma-addon), which uses storybook-addon-designs under the hood.

**Comment by lifeofmle** [comment]
@pocka Do you want me to raise a PR for allowing private Figma files?

Here is what I am thinking
- Add the Figma API key in the `.storybook/config.js`
- When loading the Figma frame use the API key in the request

**Comment by pocka** [comment]
@lifeofmle 
Yeah, it would be so helpful! But there are few things to keep in mind:

- an API key should be optional, in order to allow using the addon without API keys
- we also need per-design-API-key for advanced use-cases (look for an API key for the design then global one)

**Comment by pocka** [comment]
Hi all,

Figma announced [an official private embeds](https://www.figma.com/blog/announcing-live-figma-embeds/)! So you no longer need to include a token to use API in JavaScript code 🔒 

I'll remove the experimental private embeds support that was introduced in `v5.3.0-alpha.0` by stable release. If you're using that one, please switch to official private embeds.

To embed a private file is now super easy: copy-and-paste an URL of your Figma file (or Frame), just same as for public files. Figma app inside `<iframe>` automatically detects whether it's a private then show users a sign-in UI if needed.

I tested the feature at this repo's example with my private files and confirmed it works as intended. If you encountered a bug, please create a new issue with clear title and description (e.g. "Figma private embeds' sign-in button doesn't work").
