### ISSUE TITLE
Should @figspec/react be a dependency instead of a devDependency?

### ISSUE THREAD

**Issue by kaelig** [pocka/storybook-addon-designs#80]
As seen in:

https://github.com/pocka/storybook-addon-designs/blob/2e0b7631cc3a90a013c9b525436510a46af512a2/packages/storybook-addon-designs/package.json#L22

I'm asking because when using the latest alpha of `storybook-addon-designs`, `6.0.0-alpha.2`, I had to separately install `@figspec/react` or my project wouldn't compile.

PS: thank you for this awesome addon! ❤️

**Comment by pocka** [comment]
The reason behind not including the packages (`@figspec/react` and `@figspec/components`) is an attempt to reduce package dependencies: package managers download unused packages even if a user doesn't use Figspec preview.

https://storybook-addon-designs-rhgclupaa.vercel.app/?path=/story/docs-figma-figspec-readme

I may change the strategy in the future but will keep as-is in alpha releases.

**Comment by kaelig** [comment]
Thank you @pocka, that makes total sense, I appreciate the care you put in ensuring your plugin doesn’t bloat people's builds. I'm currently trying to speed up Storybook build times on a very large codebase, so I'm thankful!
