### ISSUE TITLE
iframes not loaded properly

### ISSUE THREAD

**Issue by iwan-uschka** [pocka/storybook-addon-designs#83]
If you export multiple stories in a story file containing multiple designs (type `iframe`) the iframes won't be loaded properly:
- ✅ hard refresh storybook => loads Story1 => loads Design1 of Story1
- ✅ click on tab Design2 => loads Design2 of Story1
- ❌ click on link Story2 => loads Story2 => doesn't load Design1 of Story2 but Design1 of Story1
- ❌ click on tab Design2 => doesn't load Design2 of Story2 but Design2 of Story1

It always seems to be one story behind.

Don't know how to provide a code example so i post one which can be used instantly in any setup containing

- react@17.0.1
- storybook-addon-design@5.4.4
- typescript@4.1.3

```
import { ReactNode, FC } from 'react';
import { Story, Meta } from '@storybook/react';
import { withDesign, config } from 'storybook-addon-designs';

const SomeComponent: FC = () => {
  return <>SOME COMPONENT CONTENT</>;
};

export default {
  title: 'some title',
  component: SomeComponent,
  decorators: [withDesign],
} as Meta;

interface DummyProps {
  description?: ReactNode;
}

const Dummy: Story<DummyProps> = ({ description }) => <div>{description}</div>;

export const Story1 = Dummy.bind({});
Story1.args = {
  description: 'TODO',
};
Story1.parameters = {
  design: config([
    {
      name: 'Tables?',
      type: 'iframe',
      url: 'http://shouldiusetablesforlayout.com/',
    },
    {
      name: 'Smallest',
      type: 'iframe',
      url: 'http://www.guimp.com/',
    },
  ]),
};

export const Story2 = Dummy.bind({});
Story2.args = {
  description: 'TODO',
};
Story2.parameters = {
  design: config([
    {
      name: 'Plaiceholder',
      type: 'iframe',
      url: 'https://plaiceholder.co/',
    },
    {
      name: 'AudioMass',
      type: 'iframe',
      url: 'https://audiomass.co/',
    },
  ]),
};
```

**Comment by pocka** [comment]
This was due to the addon uses indexes as rendering keys and fixed in v5.4.5.

[You can check it on the Vercel build](https://storybook-addon-designs-4potv4b3h.vercel.app/?path=/story/tests-issues-83--story-2)

**Comment by iwan-uschka** [comment]
Big thumbs up and thank you!! It now works.

**Comment by iwan-uschka** [comment]
Unfortunately the same issue occurs if a story has just a single design asset set.

**Comment by pocka** [comment]
@iwan-uschka Would you mind providing a repro? (or creating a new issue?)

**Comment by iwan-uschka** [comment]
For the record: tested again in version 7.0.0 without any issues.
