### ISSUE TITLE
Using a Figma group causes an error

### ISSUE THREAD

**Issue by shamilovtim** [pocka/storybook-addon-designs#93]
Attempting to link to a Figma group like this:

<img width="240" alt="Screen Shot 2021-03-25 at 2 54 04 AM" src="https://user-images.githubusercontent.com/3495974/112431444-e920c280-8d15-11eb-8ac1-159b693c8199.png">

Throws the following error:

<img width="670" alt="Screen Shot 2021-03-25 at 2 57 36 AM" src="https://user-images.githubusercontent.com/3495974/112431472-f473ee00-8d15-11eb-83e2-325658d94fbd.png">

**Comment by pocka** [comment]
You can't embed non-root nodes/groups. Both `type: "figma"` and `type: "experimental-figspec"` only support frame/file embeds. If the error happens while embedding frames/files, please provide more context or information.

> Put a design parameter into your story with type: "experimental-figspec" and url pointing your Figma file/frame/prototype. You also need accessToken representing your Figma Personal Access Token.

https://storybook-addon-designs-karlrts6b-pocka.vercel.app/?path=/story/docs-figma-figspec-readme--page
