### ISSUE TITLE
Add styling to Figma wrapper using parameters. 

### ISSUE THREAD

**Issue by matwii** [pocka/storybook-addon-designs#98]
**Is your feature request related to a problem? Please describe.**
I can't figure out how to add styling to the wrapper where Figma designs are showing. I've tried using: 
``` parameters: {
    design: {
      type: "figma",
      url: "https://www.figma.com/file/Na54d42QCGJdoSwONDMOwz/Navigasjon?node-id=782%3A647",
      style: { backgroundColor: "white" },  // color: white
    },
  },
```

But it dosn't seem to work. 
Would also like this to work with figspec. 

**Describe the solution you'd like**
I would like to specify the styles like in the example above. I saw that it was possible with doc blocks, but I couldn't figure out how to combine doc blocks and a story page. 

**Describe alternatives you've considered**
I tried using Doc Blocks, but couldn't figure it out because of missing documentation.

**Design types**

- [x] `figma`
- [x] `experimental-figspec`
- [ ] `link`
- [ ] `image`
- [ ] `iframe`

**Comment by pocka** [comment]
This addon does not provide a way to customize addon UI styles. Instead, you should use Storybook's [theming feature](https://storybook.js.org/docs/react/configure/theming).

Speaking of the Doc Blocks, the usage is described [here](https://storybook-addon-designs-pocka.vercel.app/?path=/docs/docs-advanced-usage--embed-multiple-designs#doc-blocks) (this is for v6-beta but no big changes from v5.4). Doc Blocks are just simple React components: you can pass `style` or `class` props to them and it should work.

---

If you see any inconvenient hard-coded colors in the addon UI, please open a new issue as a bug report. The addon UI should match the Storybook theme as much as possible.
